"""Gate 2 — ancestry admission.

Policy-driven, first-match-wins. Can refuse even when Gate 1 succeeded
(e.g. a row recovered as a "collective echo" gets refused because we
don't want collective echoes weighted into future retrieval).

Every decision is stamped with ``admission_policy_version`` so re-runs
can detect a policy change and route through the monotonic-in-tightness
table in ``rerun.py``.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from .constants import (
    ADMISSION_POLICY_VERSION,
    SENTINEL_UNRECOVERABLE_SOURCE,
    Gate2Reason,
)
from .gate1 import Gate1Result


@dataclass(frozen=True)
class Gate2Result:
    """Admit/refuse + reason + version stamp."""

    admit: bool
    reason: Gate2Reason
    policy_version: str
    decided_at: str  # ISO-8601 UTC.
    note: str = ""

    def to_metadata(self) -> dict[str, Any]:
        """Serialize for storage on the row's metadata block.

        Stored decisions feed the re-run comparison; keep this stable.
        """
        return {
            "admission_admit": self.admit,
            "admission_reason": self.reason.value,
            "admission_policy_version": self.policy_version,
            "admission_decided_at": self.decided_at,
            "admission_note": self.note,
        }


@dataclass
class AdmissionPolicy:
    """Configurable admission policy.

    Defaults are deliberately permissive on the *recovered* side and
    refuse the structural-bug categories (collective echo, blocked
    sources). Override per-importer when needed.
    """

    # Sources we never admit, regardless of recovery success. E.g. a
    # legacy "collective" channel where messages were aggregated
    # without per-author provenance.
    blocked_source_types: frozenset[str] = field(
        default_factory=lambda: frozenset({"collective", "anonymous-aggregate"})
    )

    # Tags on the row that mark it as a "collective echo" — content
    # generated by no specific author but stored as if authored.
    collective_echo_tags: frozenset[str] = field(
        default_factory=lambda: frozenset({"collective-echo", "ambient", "egregore"})
    )

    # When True, deprecated-vocab recoveries are admitted with their
    # remapped source. Set False to force review-queue routing for
    # deprecated rows.
    allow_deprecated_remap: bool = True


def _normalize_tags(tags: Any) -> set[str]:
    if not isinstance(tags, Iterable) or isinstance(tags, (str, bytes)):
        return set()
    out: set[str] = set()
    for tag in tags:
        if isinstance(tag, str):
            out.add(tag.strip().lower())
    return out


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def admit(
    row: Mapping[str, Any],
    gate1: Gate1Result,
    policy: AdmissionPolicy | None = None,
) -> Gate2Result:
    """Decide admission for a Gate-1-cleared (or failed) row.

    First-match-wins ordering:

    1. Gate-1 FAIL → REFUSE_GATE1_FAILED.
    2. Zero-event artifacts → REFUSE_ZERO_EVENT_ARTIFACT.
    3. Blocked source → REFUSE_BLOCKED_SOURCE.
    4. Collective echo tag → REFUSE_COLLECTIVE_ECHO.
    5. Deprecated-remap (if allowed) → ADMIT_DEPRECATED_REMAPPED.
    6. Recovered dict → ADMIT_RECOVERED_DICT.
    7. Known source (canonical / bare-string) → ADMIT_KNOWN_SOURCE.
    8. Otherwise → REFUSE_NO_RULE_MATCHED.
    """
    policy = policy or AdmissionPolicy()
    now = _now_iso()

    if not gate1.is_recoverable:
        # Distinguish zero-event artifact from generic gate-1 failure
        # so audit queries can pull them apart cleanly.
        if gate1.fail_reason == "zero_event_artifact":
            return Gate2Result(
                admit=False,
                reason=Gate2Reason.REFUSE_ZERO_EVENT_ARTIFACT,
                policy_version=ADMISSION_POLICY_VERSION,
                decided_at=now,
                note=gate1.fail_reason,
            )
        return Gate2Result(
            admit=False,
            reason=Gate2Reason.REFUSE_GATE1_FAILED,
            policy_version=ADMISSION_POLICY_VERSION,
            decided_at=now,
            note=gate1.fail_reason,
        )

    src = gate1.recovered_source_type
    if src == SENTINEL_UNRECOVERABLE_SOURCE:
        # Defensive — shouldn't reach here on is_recoverable=True.
        return Gate2Result(
            admit=False,
            reason=Gate2Reason.REFUSE_GATE1_FAILED,
            policy_version=ADMISSION_POLICY_VERSION,
            decided_at=now,
            note="sentinel_on_recoverable_path",
        )

    if src in policy.blocked_source_types:
        return Gate2Result(
            admit=False,
            reason=Gate2Reason.REFUSE_BLOCKED_SOURCE,
            policy_version=ADMISSION_POLICY_VERSION,
            decided_at=now,
            note=f"blocked_source:{src}",
        )

    tags = _normalize_tags(row.get("tags"))
    if tags & policy.collective_echo_tags:
        return Gate2Result(
            admit=False,
            reason=Gate2Reason.REFUSE_COLLECTIVE_ECHO,
            policy_version=ADMISSION_POLICY_VERSION,
            decided_at=now,
            note="collective_echo_tag_match",
        )

    # Distinguish recovery routes for clearer audit trails.
    from .constants import Gate1Class  # local to avoid cycle in stubs

    if gate1.cls == Gate1Class.DEPRECATED_VOCAB:
        if not policy.allow_deprecated_remap:
            return Gate2Result(
                admit=False,
                reason=Gate2Reason.REFUSE_NO_RULE_MATCHED,
                policy_version=ADMISSION_POLICY_VERSION,
                decided_at=now,
                note="deprecated_remap_disabled",
            )
        return Gate2Result(
            admit=True,
            reason=Gate2Reason.ADMIT_DEPRECATED_REMAPPED,
            policy_version=ADMISSION_POLICY_VERSION,
            decided_at=now,
            note=f"remapped_to:{src}",
        )

    if gate1.cls == Gate1Class.DICT_TRUNCATED:
        return Gate2Result(
            admit=True,
            reason=Gate2Reason.ADMIT_RECOVERED_DICT,
            policy_version=ADMISSION_POLICY_VERSION,
            decided_at=now,
            note="parent_eids_recovered_or_empty",
        )

    if gate1.cls in (Gate1Class.ALREADY_CANONICAL, Gate1Class.LEGACY_BARE_STRING):
        return Gate2Result(
            admit=True,
            reason=Gate2Reason.ADMIT_KNOWN_SOURCE,
            policy_version=ADMISSION_POLICY_VERSION,
            decided_at=now,
            note=f"source:{src}",
        )

    return Gate2Result(
        admit=False,
        reason=Gate2Reason.REFUSE_NO_RULE_MATCHED,
        policy_version=ADMISSION_POLICY_VERSION,
        decided_at=now,
        note=f"unhandled_class:{gate1.cls.value}",
    )
