"""
Root conftest.py — bootstraps a minimal test agent before any skmemory module
is imported by pytest.

Several skmemory modules (seeds.py, febs.py, soul.py, etc.) call
``get_agent_paths()`` at **module level**, which raises ``ValueError`` if no
agent directory exists under ``~/.skcapstone/agents/``.  This file runs before
pytest collects any test files, so setting ``SKCAPSTONE_HOME`` and
``SKCAPSTONE_AGENT`` here — and creating the matching directory tree — ensures
those imports always succeed in CI and other fresh environments.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from pathlib import Path

# ── Bootstrap a throw-away test agent ─────────────────────────────────────────
# Must happen at module level (not inside a fixture) so it takes effect before
# pytest imports test files that themselves import skmemory.

_TEST_AGENT_NAME = "test-agent"

# Use a temp dir so we never pollute the real ~/.skcapstone tree.
_tmp_skcapstone = tempfile.mkdtemp(prefix="skmemory_ci_")
os.environ["SKCAPSTONE_HOME"] = _tmp_skcapstone
os.environ["SKCAPSTONE_AGENT"] = _TEST_AGENT_NAME
# Ignore selectors inherited from the developer shell. Tests opt into them explicitly.
os.environ.pop("SKAGENT", None)
os.environ.pop("SKMEMORY_AGENT", None)

_agent_base = Path(_tmp_skcapstone) / "agents" / _TEST_AGENT_NAME
for _subdir in (
    "config",
    "seeds",
    "memory/short-term",
    "memory/mid-term",
    "memory/long-term",
    "logs",
    "archive",
):
    (_agent_base / _subdir).mkdir(parents=True, exist_ok=True)

# Minimal config so list_agents() finds this agent and load_config() doesn't
# blow up.
(_agent_base / "config" / "skmemory.yaml").write_text(
    "# Auto-generated by tests/conftest.py\nname: test-agent\n"
)


def _content_hash(document: dict, field: str) -> str:
    payload = {key: value for key, value in document.items() if key != field}
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return f"sha256:{hashlib.sha256(encoded).hexdigest()}"


_profiles = []
for _profile_id in (_TEST_AGENT_NAME, "lumina", "jarvis", "opus"):
    _profile = {
        "schema_version": "skcapstone.agent-profile.v1",
        "schema_revision": "1",
        "profile_id": _profile_id,
        "profile_kind": "human",
        "selectable": True,
        "fallback_eligible": True,
        "memory_principal_id": f"memory:{_profile_id}",
        "default_tools": [],
        "capability_policy_ref": "synthetic-test-policy.v1",
        "profile_revision": "1",
        "profile_hash": "",
    }
    _profile["profile_hash"] = _content_hash(_profile, "profile_hash")
    _profile_dir = Path(_tmp_skcapstone) / "agents" / _profile_id
    _profile_dir.mkdir(parents=True, exist_ok=True)
    (_profile_dir / "profile.json").write_text(json.dumps(_profile))
    _profiles.append(
        {
            key: _profile[key]
            for key in (
                "profile_id",
                "profile_kind",
                "selectable",
                "fallback_eligible",
                "memory_principal_id",
                "schema_revision",
                "profile_revision",
                "profile_hash",
            )
        }
    )

_registry = {
    "schema_version": "skcapstone.profile-registry.v1",
    "schema_revision": "1",
    "registry_revision": "synthetic-test-1",
    "profiles": _profiles,
    "registry_hash": "",
}
_registry["registry_hash"] = _content_hash(_registry, "registry_hash")
(Path(_tmp_skcapstone) / "config").mkdir()
(Path(_tmp_skcapstone) / "config" / "profile-registry.json").write_text(json.dumps(_registry))
