"""
Root conftest.py — bootstraps a minimal test agent before any skmemory module
is imported by pytest.

Several skmemory modules (seeds.py, febs.py, soul.py, etc.) call
``get_agent_paths()`` at **module level**, which raises ``ValueError`` if no
agent directory exists under ``~/.skcapstone/agents/``.  This file runs before
pytest collects any test files, so setting ``SKCAPSTONE_HOME`` and
``SKCAPSTONE_AGENT`` here — and creating the matching directory tree — ensures
those imports always succeed in CI and other fresh environments.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

# ── Bootstrap a throw-away test agent ─────────────────────────────────────────
# Must happen at module level (not inside a fixture) so it takes effect before
# pytest imports test files that themselves import skmemory.

_TEST_AGENT_NAME = "test-agent"

# Use a temp dir so we never pollute the real ~/.skcapstone tree.
_tmp_skcapstone = tempfile.mkdtemp(prefix="skmemory_ci_")
os.environ["SKCAPSTONE_HOME"] = _tmp_skcapstone
os.environ["SKCAPSTONE_AGENT"] = _TEST_AGENT_NAME

_agent_base = Path(_tmp_skcapstone) / "agents" / _TEST_AGENT_NAME
for _subdir in (
    "config",
    "seeds",
    "memory/short-term",
    "memory/mid-term",
    "memory/long-term",
    "logs",
    "archive",
):
    (_agent_base / _subdir).mkdir(parents=True, exist_ok=True)

# Minimal config so list_agents() finds this agent and load_config() doesn't
# blow up.
(_agent_base / "config" / "skmemory.yaml").write_text(
    "# Auto-generated by tests/conftest.py\nname: test-agent\n"
)
